-- Chạy bằng datasource SYSTEM_ORCLPDB, service ORCLPDB
-- Mục tiêu: tạo schema riêng cho phần Hệ quản trị CSDL

SELECT SYS_CONTEXT('USERENV', 'CON_NAME') AS current_container
FROM dual;

CREATE USER HQT_DEMO IDENTIFIED BY HQT123;

GRANT CONNECT, RESOURCE TO HQT_DEMO;
GRANT CREATE SESSION TO HQT_DEMO;
GRANT CREATE TABLE TO HQT_DEMO;
GRANT CREATE VIEW TO HQT_DEMO;
GRANT CREATE SEQUENCE TO HQT_DEMO;
GRANT CREATE PROCEDURE TO HQT_DEMO;
GRANT CREATE TRIGGER TO HQT_DEMO;
GRANT CREATE TYPE TO HQT_DEMO;

ALTER USER HQT_DEMO QUOTA UNLIMITED ON USERS;

SELECT username, account_status
FROM dba_users
WHERE username = 'HQT_DEMO';
